version: '3'

services:
    influx:
        image: influxdb
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_DB=softmngr
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_WRITE_USER=influx
            - INFLUXDB_WRITE_USER_PASSWORD=influx
    mongo:
        image: mongo
        volumes:
            - ./volumes/mongo:/data/db/

    softmngr:
        image: osallou/softmngr
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - TOKENS=ADZDEEEFEF,EZEZEZEZEZZEZ
        ports:
            - 3000:3000
